-keep class com.venti1112.edgecube.pty.PtyBridge { *; }
-keep interface com.venti1112.edgecube.pty.FrameListener { *; }
-keep class com.venti1112.edgecube.files.ArchiveBridge { *; }
-keep interface com.venti1112.edgecube.files.ArchiveProgressListener { *; }
-keep class com.venti1112.edgecube.ftp.FtpBridge { *; }
-keep class com.venti1112.edgecube.ssh.SshBridge { *; }
